version: '3'
services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=starcode'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    restart: always

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
    restart: always
    links:
      - postgres